### ISSUE TITLE
Clarification in the README 

### ISSUE THREAD

**Issue by gmichalo** [simonlevine/clinical-longformer#1]
Hello,

I was wondering if you can clarify if you pre-train the BiomedRobertaBase model on mimic and then convert it to the LongFormer version or did you pre-train the LongFormer version on MIMIC?

The reason I am asking is that in one part of the README it stated that  "We pre-train the Longformer on MIMIC-III + MIMIC-CXR data for ~1000 epochs" but in another part, it is stated, "We pre-train AllenAI/BiomedRobertaBase as a default, as pre-training with global attention results in severe memory issues..."

Thank you in advance.

**Comment by simonlevine** [comment]
Sorry for the confusion, there was a mistake and readme is fixed. The original plan was to do MLM with global attention and release that model. However, we ran into severe memory issues when attempting 4096-token MLM. So, we instead reinstantiate after 512-token MLM using biomed-RoBERTa, and use global attention just for end-to-end classification in this case. This still trains global attention (encoder was not frozen in our trials), but not in terms of learning a language model. We plan on and suggest attempting to re-train MLM with more data and global attention, but also suggest waiting until custom "longformers" have better interoperability with Huggingface (as you can see this is still housed under "roberta"). If you are in the position of having more resources, we suggest training a Longformer from scratch as well.
