### ISSUE TITLE
Tokenizer

### ISSUE THREAD

**Issue by agarfau** [simonlevine/clinical-longformer#3]
Hi!
How would you suggest to load a tokenizer from your pretrained model? Using `AutoTokenizer` or `RobertaTokenizerFast` and `from_pretrained()` would result in `TypeError: special token bos_token has to be either str or AddedToken but got: <class 'dict'>`.

Thanks!

**Comment by simonlevine** [comment]
Hi, please refer to `./classifier_pipeline/classifier_one_label.py` to see how we import the Tokenizer class for our experiments.
