### ISSUE TITLE
Pulling model with Huggingface 4.8 

### ISSUE THREAD

**Issue by amoldwin** [simonlevine/clinical-longformer#4]
Hello, I originally had trouble pulling the `simonlevine/bioclinical-roberta-long` model with newer versions of huggingface, so I needed to use the fix described at https://github.com/huggingface/transformers/issues/9588 to load the roberta class with longformer attention.
Basically the solution mentioned there just adds these 3 lines to the forward function of the 'Longformer Attention' class:
```
        attention_mask = attention_mask.squeeze(dim=2).squeeze(dim=1)
        # is index masked or global attention
        is_index_masked = attention_mask < 0
        is_index_global_attn = attention_mask > 0
        is_global_attn = any(is_index_global_attn.flatten())
```

**Comment by simonlevine** [comment]
Hi! Thanks for the input and good catch. Transformers seems to change very quickly! I will work on specifying this in the HF model zoo when I get the chance.
